name: R-CMD-check

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install the package
        run: |
          remotes::install_local()
        shell: Rscript {0}

      - name: Print package contents
        run: |
          library(vsreport)
          ls("package:vsreport")
        shell: Rscript {0}

      - name: List installed packages
        run: |
          installed.packages()
        shell: Rscript {0}

      - name: Run tests
        run: |
          install.packages('testthat')
          library(vsreport)
          testthat::test_dir('tests/testthat')
        shell: Rscript {0}

      - name: Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
